name: pycon-ds-2018
channels:
- conda-forge
- defaults
dependencies:
- bokeh=0.12.9
- ipython=6.2.1
- matplotlib=2.2.2
- notebook=5.4.1
- numpy=1.13.3
- pandas=0.22.0
- pip=9.0.1
- python=3.6.3
- requests=2.18.4
- scikit-learn=0.19.0
- scipy=0.19.1
- seaborn=0.8.1
- setuptools=36.6.0
- statsmodels=0.8.0
